### ISSUE TITLE
Not all boards have json, so gracefully fallback if not present

### ISSUE THREAD

**Issue by hamslabs** [adafruit/Adafruit_CircuitPython_Slideshow#28]
adafruit_slideshow.py imports json and it isn't defined anywhere in circuitpython or the bundle.

**Comment by dhalbert** [comment]
`json` is built into most but not all builds of CIrcuitPython. There is not a separate library. So you may be using a small build that doesn't have room, or an old build (it used to be called `ujson`).

**Comment by dhalbert** [comment]
The text file support assumes the `json` module exists, which isn't true on SAMD21 builds. The code should fall back gracefully if `import json` fails.
@FoamyGuy

**Comment by FoamyGuy** [comment]
I can make this change tonight. I will catch the ImportError and add a note indicating text slides require `json`
