### ISSUE TITLE
IndexError: list index out of range (maybe cause' it's one image?)

### ISSUE THREAD

**Issue by ptorrone** [adafruit/Adafruit_CircuitPython_Slideshow#3]
Traceback (most recent call last):
  File "code.py", line 10, in <module>
  File "adafruit_slideshow.py", line 264, in update
  File "adafruit_slideshow.py", line 293, in advance
IndexError: list index out of range

files attached on flash (.zip). unzip and put on hallowing.

[flash.zip](https://github.com/adafruit/Adafruit_CircuitPython_Slideshow/files/2469753/flash.zip)

**Comment by kattni** [comment]
I am able to replicate this with my setup. Yes it appears to be due to only one image. Troubleshooting this now.

**Comment by kattni** [comment]
Issue fixed by #5 . Thanks again, @ptorrone for finding this!

**Comment by ptorrone** [comment]
tested here too, it works! thankya'
