### ISSUE TITLE
os.path issue

### ISSUE THREAD

**Issue by verystealthy** [adafruit/Adafruit_CircuitPython_Slideshow#31]
Hello! It looks like commit #8a6a473 broke the library on CircuitPython. I have very limited understanding of this whole thing, but, from what I can gather, the change to `os.path` is causing an error because `os.path` is not part of the built-in CircuitPython `os` module. In other words, CircuitPython doesn't really now what os.path is. 

Error on CircuitPython 6.0.0 code running on a Matrix Portal M4 board:

> Traceback (most recent call last):
>File "code.py", line 24, in <module>
>File "adafruit_slideshow.py", line 248, in __init__
>File "adafruit_slideshow.py", line 251, in <listcomp>
>AttributeError: 'module' object has no attribute 'path'

Removing references to `os.path` from adafruit_slideshow.py and going back to `folder + f` (and adding the trailing "/" to the path) solves the issue.

**Comment by ladyada** [comment]
oi sorry about that...not sure how that code was written and run. reverted for now!
